### PR TITLE
Combining Details page into dev branch

### PR DESCRIPTION
**Pull request by NoahRen25**
Yes

### CODE REVIEW

**Review by Aaditya-Tiwari — APPROVED** [review]
Looks breathtaking🥳🥳🤯🤯!

**Review by kevinniu79 — APPROVED** [review]
Very stimulating and intelligible code

**Review by hraetz — APPROVED** [review]
These changes are truly enthralling, ravishingly irresistible, and would certainly be the type to perambulate to my residence's stoop and verbally aggrandize me.

**Review by jdong03 — APPROVED** [review]
Looks possibly satisfactory

**Pull request merged**
